# Generated by Django 5.0.6 on 2024-07-18 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_list_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='_shared_with',
            field=models.ManyToManyField(related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
