# Generated by Django 5.0.6 on 2024-07-18 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_list__shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='_shared_with',
            field=models.ManyToManyField(related_name='lists_with_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
